import random

class PhrasePlaceHolder:
    def __init__(self):
        self.placeholders = [
            "Laissez libre cours à votre imagination, commencez à écrire ici...",
            "Chaque mot compte, débutez votre histoire maintenant...",
            "Un texte inspiré commence par une pensée, écrivez-la...",
            "Exprimez-vous, vos idées méritent d'être notées...",
            "Un mot peut changer le monde, écrivez-le ici...",
            "L'inspiration frappe à tout moment, saisissez-la ici...",
            "Votre aventure commence maintenant...",
            "Les grandes idées commencent par de petits mots...",
            "Laissez vos pensées s'envoler sur cette page...",
            "Écrivez ce qui vous passe par la tête, chaque mot compte...",
            "Les mots sont puissants, utilisez-les bien...",
            "Un voyage de mille mots commence par un seul ici...",
            "Laissez vos idées s'exprimer librement...",
            "Chaque histoire mérite d'être racontée, commencez ici...",
            "Un mot peut ouvrir un univers de possibilités...",
            "La première phrase est toujours la plus difficile, commencez ici...",
            "Libérez votre créativité, commencez à écrire...",
            "Les mots peuvent faire des miracles, commencez maintenant...",
            "Un mot écrit ici peut inspirer des milliers...",
            "Un mot en amène un autre, écrivez ce premier mot ici...",
            "L'inspiration vient en écrivant, laissez votre plume s'exprimer ici...",
            "Chaque idée commence par une première lettre, écrivez la vôtre ci-dessous...",
            "Les mots se tissent au fur et à mesure, commencez par celui-ci...",
            "Écrire, c'est donner vie aux pensées, débutez ici...",
            "Un texte naît d'une première pensée, posez-la ici...",
            "Tout récit débute par une simple phrase, la vôtre commence ici...",
            "De petites idées naissent de grandes créations, laissez la vôtre s'épanouir ici...",
            "Le début d'une histoire est souvent le plus simple, commencez ici...",
            "Chaque mot que vous tapez ouvre une nouvelle porte, commencez par celle-ci...",
            "Écrire, c'est voyager avec des mots, commencez le vôtre ici...",
            "Laissez votre plume danser sur la page, l'histoire commence ici...",
            "Chaque mot que vous écrivez est une étoile dans votre univers littéraire...",
            "Écrivez avec le cœur, laissez vos émotions guider chaque ligne...",
            "Transformez vos pensées en poésie, commencez maintenant...",
            "Un mot à la fois, créez un chef-d'œuvre littéraire...",
            "Les mots ont des ailes, laissez-les s'envoler sur cette page...",
            "Écrire, c'est peindre avec des mots, commencez votre tableau ici...",
            "Un simple mot peut déclencher une avalanche d'idées, écrivez-le...",
            "Chaque phrase est une brique dans le château de votre imagination...",
            "Plongez votre plume dans l'encre de vos rêves, commencez ici...",
            "Écrivez comme si personne ne lisait, laissez libre cours à votre créativité...",
            "Les mots sont des trésors, trouvez les vôtres et partagez-les...",
            "Chaque idée est une graine, plantez-la et regardez-la grandir ici...",
            "Laissez vos pensées couler comme une rivière sur cette page...",
            "Un mot peut illuminer l'obscurité, écrivez-le et partagez sa lumière...",
            "Votre histoire attend d'être écrite, il ne manque que vous...",
            "Le silence de la page blanche appelle votre voix...",
            "Offrez au monde un fragment de votre univers intérieur...",
            "Chaque lettre est un pas vers quelque chose de grand...",
            "Prenez une inspiration profonde et laissez les mots venir...",
            "Votre plume est une baguette magique, créez l'enchantement...",
            "Il suffit d'un mot pour briser le silence de la page...",
            "L'encre de vos pensées n'attend qu'à couler ici...",
            "Racontez ce que personne d'autre ne peut raconter...",
            "Votre voix est unique, donnez-lui un espace ici...",
            "Derrière chaque mot se cache un monde à découvrir...",
            "Osez écrire ce que votre cœur murmure...",
            "Les plus belles histoires commencent par un simple geste...",
            "La page est un miroir, elle reflétera ce que vous lui confiez...",
            "Donnez forme à l'invisible, écrivez ce que vous ressentez...",
            "Chaque phrase que vous écrivez est un cadeau au futur...",
            "Les mots sont des ponts entre votre esprit et le monde...",
            "Laissez votre imagination tisser sa toile ici...",
            "Aujourd'hui est le jour parfait pour commencer à écrire...",
            "Votre récit est une mélodie, composez la première note...",
            "Même un seul mot peut contenir tout un roman...",
            "L'aventure littéraire commence au bout de vos doigts...",
            "Confiez vos secrets à cette page, elle saura les garder...",
            "Écrivez sans filtre, la magie opère dans la spontanéité...",
            "Chaque mot posé ici est une victoire sur le vide...",
            "Votre imagination est sans limites, cette page aussi...",
            "Les histoires dorment en vous, réveillez-les doucement...",
            "Un crayon, une page, un monde infini de possibilités...",
            "Laissez la curiosité guider vos mots sur cette page...",
            "Vos pensées sont précieuses, offrez-leur un écrin ici...",
            "Le premier mot est une porte, poussez-la sans hésiter...",
            "Écrivez comme on respire, naturellement et sans effort...",
            "Chaque texte est une empreinte unique de son auteur...",
            "L'écriture est un voyage, et cette page est votre point de départ...",
            "Transformez le quotidien en extraordinaire avec vos mots...",
            "Il y a une histoire en vous qui ne demande qu'à sortir...",
            "Les mots que vous cherchez vous trouveront en chemin...",
            "Faites de cette page le terrain de jeu de votre esprit...",
            "Votre stylo est chargé de rêves, libérez-les ici...",
            "Chaque paragraphe est un nouveau chapitre de votre créativité...",
            "L'écriture commence là où le doute s'arrête...",
            "Posez vos idées ici comme on sème des graines au printemps...",
            "Cette page est une toile vierge, peignez-la avec des mots...",
            "Écrivez l'histoire que vous aimeriez lire...",
            "Les mots naissent du silence, écoutez puis écrivez...",
            "Votre plume est plus forte que vous ne le pensez...",
            "Chaque virgule est une respiration, chaque point un battement de cœur...",
            "L'écriture est la plus belle forme de liberté...",
            "Donnez des ailes à vos pensées, elles méritent de voler...",
            "Un texte sincère vaut mille textes parfaits...",
            "Laissez vos émotions dessiner des phrases sur cette page...",
            "La beauté des mots réside dans leur sincérité...",
            "Chaque jour apporte une nouvelle histoire à écrire...",
            "L'important n'est pas de bien écrire, mais d'écrire vrai...",
            "Vos mots ont le pouvoir de toucher des âmes...",
            "La page blanche est une invitation, acceptez-la...",
            "Écrivez pour vous d'abord, le reste suivra...",
            "Chaque mot est un fil qui tisse la tapisserie de votre récit...",
            "Ici commence le chemin entre votre pensée et le monde...",
            "Les rêves deviennent réels quand on les couche sur le papier...",
            "Votre histoire est la seule que personne d'autre ne peut écrire...",
            "Laissez vos doigts traduire ce que votre esprit imagine...",
            "Un océan de mots vous attend, plongez sans retenue...",
            "L'écriture est un acte de courage, soyez brave...",
            "Murmurez vos pensées à cette page, elle vous écoute...",
            "Créez un monde où tout est possible, mot après mot...",
            "L'inspiration est partout, il suffit de la capturer ici...",
            "Vos mots sont des étoiles filantes, attrapez-les au vol...",
            "Chaque nouvelle ligne est une chance de recommencer...",
            "Écrivez avec la même passion que celle qui vous anime...",
            "La page attend votre empreinte, laissez votre marque...",
            "Les meilleures histoires naissent de l'inattendu...",
            "Votre clavier est un instrument, jouez votre symphonie...",
            "Chaque espace entre les mots est un souffle de vie...",
            "Laissez le rythme de vos pensées guider votre écriture...",
            "Les mots sont des couleurs, peignez votre arc-en-ciel...",
            "Osez la première phrase, les suivantes viendront d'elles-mêmes...",
            "Votre texte est un jardin, cultivez-le avec soin...",
            "L'écriture est une danse, laissez les mots mener le bal...",
            "Chaque mot posé est une pierre sur le chemin de votre récit...",
            "La magie de l'écriture commence à la première lettre...",
            "Vos idées sont des diamants bruts, polissez-les ici...",
            "Écrivez comme si chaque mot était le dernier, avec intensité...",
            "La page vous tend la main, prenez-la et avancez ensemble...",
            "Un mot après l'autre, vous construisez quelque chose de beau...",
            "Laissez votre âme parler à travers vos mots...",
            "L'écriture est un refuge, trouvez le vôtre ici...",
            "Chaque phrase est un souffle nouveau dans votre récit...",
            "Vos mots peuvent faire sourire, pleurer, rêver... commencez...",
            "Le monde a besoin de votre regard, partagez-le par l'écriture...",
            "Écrivez sans crainte du jugement, cette page est votre alliée...",
            "Les pensées les plus simples font souvent les plus beaux textes...",
            "Votre créativité est un trésor, ouvrez le coffre ici...",
            "L'écriture transforme l'éphémère en éternel...",
            "Chaque mot que vous tapez rapproche votre rêve de la réalité...",
            "Prenez votre temps, les mots justes viendront naturellement...",
            "La première ligne est un saut dans le vide, et c'est grisant...",
            "Vos pensées méritent d'exister au-delà de votre esprit...",
            "Ici, il n'y a pas de règles, seulement votre voix...",
            "Laissez l'écriture vous surprendre, elle sait où elle va...",
            "Chaque texte est une aventure dont vous êtes le héros...",
            "Les mots sont vos compagnons de route, choisissez-les bien...",
            "Votre imagination est un feu, alimentez-le mot après mot...",
            "La page blanche n'est pas un obstacle, c'est une promesse...",
            "Écrivez ce qui brûle en vous, les mots éteindront la flamme...",
            "L'écriture est un dialogue avec soi-même, engagez la conversation...",
            "Chaque nouvelle phrase ouvre un horizon inexploré...",
            "Vos mots sont des graines semées dans le jardin du lecteur...",
            "Laissez votre cœur dicter et vos doigts suivront...",
            "Le talent s'éveille à la première ligne, commencez maintenant...",
            "Les mots sont des voyageurs, envoyez-les explorer le monde...",
            "Votre récit est un fleuve, laissez-le trouver son cours...",
            "Écrire, c'est respirer autrement...",
            "Chaque mot est une étincelle dans la nuit de la page blanche...",
            "L'écriture est le plus court chemin entre deux âmes...",
            "Faites confiance à votre instinct, les bons mots suivront...",
            "La beauté de l'écriture, c'est qu'elle vous appartient...",
            "Vos phrases sont des chemins que d'autres emprunteront un jour...",
            "Un texte commence toujours par un acte de foi, croyez en vous...",
            "Les histoires vivent en nous, l'écriture leur ouvre la porte...",
            "Écrivez avec le même émerveillement qu'un enfant qui découvre...",
            "Votre voix intérieure a tant à dire, laissez-la s'exprimer...",
            "La plus belle page est celle que vous êtes sur le point d'écrire...",
            "Les mots sont des oiseaux, ouvrez la cage et regardez-les voler...",
            "Chaque lettre est un battement d'aile vers de nouveaux horizons...",
            "L'écriture est une fenêtre ouverte sur l'infini...",
            "Votre texte sera aussi unique que l'empreinte de vos doigts...",
            "Les rêves s'écrivent les yeux ouverts, commencez le vôtre...",
            "Un mot sincère vaut plus que mille mots parfaits...",
            "Laissez chaque phrase vous emmener plus loin que la précédente...",
            "L'écriture est un art, et vous en êtes l'artiste...",
            "Vos mots portent en eux la chaleur de votre pensée...",
            "Chaque début est un acte de bravoure, soyez audacieux...",
            "La page est patiente, elle attendra que vous soyez prêt...",
            "Écrivez pour le plaisir, le talent viendra avec la passion...",
            "Votre histoire commence exactement ici, exactement maintenant...",
            "Les plus grands voyages commencent par un simple mot...",
            "Laissez l'écriture vous guider vers des terres inconnues...",
            "Un mot posé ici aujourd'hui peut résonner pour toujours...",
            "Votre plume est votre boussole, suivez-la sans hésiter...",
            "Chaque texte est une lettre d'amour à la vie...",
            "L'écriture est un souffle, expirez vos pensées sur cette page...",
            "Les mots justes existent déjà en vous, laissez-les émerger...",
            "Cette page est le début de quelque chose de merveilleux...",
            "Écrivez avec audace, corrigez avec douceur...",
            "Vos mots sont le reflet de votre monde intérieur...",
            "Chaque histoire écrite est un pas vers l'immortalité...",
            "L'écriture est une conversation intime avec l'univers...",
            "Prenez la plume et dessinez votre destin mot à mot..."
        ]

    def get_random_phrase(self):
        return random.choice(self.placeholders)
